name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-client:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: npm ci
        working-directory: ./app/client
      - run: npm run build
        working-directory: ./app/client
      - run: npm test
        working-directory: ./app/client
  test-server:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: mongod --config "./test.mongod.conf" &
        working-directory: ./app/server
      - run: npm ci
        working-directory: ./app/server
      - run: npm test
        working-directory: ./app/server